version: 2
updates:
  - package-ecosystem: "npm" # Supported values: npm, yarn, etc.
    directory: "/" # Root directory containing package.json
    schedule:
      interval: "weekly" # Check for updates every week
    groups:
      # Minor and patch updates for all production dependencies (e.g., React, Next.js, UI libraries)
      production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        # Optionally exclude specific production dependencies known to break builds
        # exclude-patterns:
        #   - "problematic-lib"

      # Minor, patch, and major updates for all development dependencies (e.g., testing tools, linters, build tools)
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
          - "major"
        # Optionally exclude specific dev dependencies known to cause issues
        # exclude-patterns:
        #   - "another-problematic-dev-tool"

      # Isolate major updates for core Next.js/React packages to a separate group for easier review
      core-major-updates:
        patterns:
          - "next"
          - "react"
          - "react-dom"
        update-types:
          - "major"
